### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ivesbrito** [fagundes/ZffHtml2pdf#1]
Boa noite, 

Poderia me dar uma força com relação à modificação dos parâmetros que são repassados no construtor do html2pdf?

Não consigo alterá-los a partir do meu controller, só estou conseguindo diretamente no Html2PdfRenderer. :(

**Comment by fagundes** [comment]
Boa noite @ivesbrito,

Por enquanto, uma possível solução é modificar os parâmetros do construtor via arquivo de configuração, dá uma olhada aqui [Configuring html2pdf constructor](http://fagundes.github.io/ZffHtml2pdf/configuring/).

Na controller, ainda não é possível, mas realmente é útil, caso se tenha que gerar diversos pdfs com parâmetros diferentes entre si. Uma possível solução na controller exigiria mudanças em código. Até tenho umas ideias, assim que tiver um tempo eu implemento. Mas se sinta livre para contribuir também! ;)

Qualquer dúvida, sugestão, manda aí!

**Comment by fagundes** [comment]
@ivesbrito acabei de atualizar a lib para suportar a mudança dos parâmetros usados pelo construtor do html2pdf na controller. 

A documentação [Configuring html2pdf constructor](http://fagundes.github.io/ZffHtml2pdf/configuring/) foi atualizada, e explica como fazer isso a partir da controller.

**Comment by ivesbrito** [comment]
@fagundes, muito obrigado cara!!! Estarei verificando e utilizando do recurso disponibilizado!!!

Thanks!!
